-- 分类表
DROP TABLE IF EXISTS category;
CREATE TABLE IF NOT EXISTS category (
`cate_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`cate_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '分类名称',
`p_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级分类ID',
`keywords` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '分类关键字',
`title` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '分类标题',
`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分类描述',
`sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
`is_show` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否显示',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
PRIMARY KEY (`cate_id`),
UNIQUE INDEX uniq_cate_name (`cate_name`),
UNIQUE INDEX uniq_p_id (`p_id`),
UNIQUE INDEX uniq_sort (`sort`),
UNIQUE INDEX uniq_is_show (`is_show`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '商品分类表';

-- 商品表
DROP TABLE IF EXISTS goods;
CREATE TABLE IF NOT EXISTS goods (
`goods_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品主键ID',
`cate_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-分类ID',
`main_title` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商品主标题',
`sub_title` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品二级标题',
`price` DECIMAL(8,2) NOT NULL DEFAULT 0 COMMENT '商品价格',
`old_price` DECIMAL(8,2) NOT NULL DEFAULT 0 COMMENT '商品原价',
`buy_num` SMALLINT NOT NULL DEFAULT 0 COMMENT '购买人数',
`goods_img` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品图片',
`is_sale` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否上架',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
PRIMARY KEY (`goods_id`),
UNIQUE INDEX uniq_cate_id (`cate_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '商品表';

-- 商品详情表
DROP TABLE IF EXISTS goods_detail;
CREATE TABLE IF NOT EXISTS goods_detail (
`goods_id` INT UNSIGNED NOT NULL COMMENT '外键-商品ID',
`detail` TEXT NOT NULL COMMENT '商品描述',
PRIMARY KEY (`goods_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '商品详情表';

-- 订单表
DROP TABLE IF EXISTS `order`;
CREATE TABLE IF NOT EXISTS `order` (
`order_id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '主键-订单号',
`user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-用户ID',
`goods_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-商品ID',
`goods_num` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商品数量',
`total_price` DECIMAL(8,2) NOT NULL COMMENT '商品总金额',
`order_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '订单状态，0为未支付，1为已支付，2为已发货，3为订单关闭',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '下单时间',
`pay_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付时间',
`send_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '发货时间',
`close_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '订单关闭时间',
PRIMARY KEY (`order_id`),
INDEX idx_goods_id (`goods_id`),
INDEX idx_user_id (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '订单表';

-- 商品评论表
DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment` (
`comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
`goods_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-商品ID',
`user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-用户ID',
`order_id` INT(10) UNSIGNED ZEROFILL NOT NULL DEFAULT 0 COMMENT '订单ID',
`comment_content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论内容',
`comment_img` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论图片',
`comment_start` TINYINT(1) UNSIGNED NOT NULL DEFAULT 5 COMMENT '星级',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '评价时间',
PRIMARY KEY (`comment_id`),
INDEX idx_user_id (`user_id`),
INDEX idx_goods_id (`goods_id`),
INDEX idx_order_id (`order_id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '商品评价表';

-- 购物车表
DROP TABLE IF EXISTS `cart`;
CREATE TABLE IF NOT EXISTS `cart` (
`cart_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`goods_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-商品ID',
`user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-用户ID',
`goods_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商品数量',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
PRIMARY KEY (`cart_id`),
INDEX idx_user_id (`user_id`),
INDEX idx_goods_id (`goods_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '购物车';

-- 收藏表
DROP TABLE IF EXISTS `collect`;
CREATE TABLE IF NOT EXISTS `collect` (
`collect_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`goods_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-商品ID',
`user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-用户ID',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
PRIMARY KEY (`collect_id`),
INDEX idx_user_id (`user_id`),
INDEX idx_goods_id (`goods_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '收藏表';

-- 用户地址表
DROP TABLE IF EXISTS `user_address`;
CREATE TABLE IF NOT EXISTS `user_address` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
`user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '外键-用户ID',
`consignee` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '收货人姓名',
`province` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '省份',
`city` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '市',
`county` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '县/区',
`street` VARCHAR(255) NOT NULL DEFAULT '街道地址',
`tel` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '联系电话',
`postcode` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '邮政编码',
PRIMARY KEY (`id`),
INDEX idx_user_id (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户收货地址，可以有多个';

-- 用户信息表
DROP TABLE IF EXISTS `userinfo`;
CREATE TABLE IF NOT EXISTS `userinfo` (
`user_id` INT UNSIGNED NOT NULL COMMENT '外键-用户ID',
`user_nick` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户昵称',
`user_avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像',
`balance` DECIMAL(8,2) NOT NULL DEFAULT 0 COMMENT '账户余额',
`integral` SMALLINT NOT NULL DEFAULT 0 COMMENT '用户积分',
INDEX idx_user_id (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户信息表，保存用户余额，积分等数据';

-- 用户表
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
`user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键-用户ID',
`user_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '账号',
`user_email` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '',
`user_tel` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '联系电话',
`user_pwd` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
`old_pwd` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '曾用密码',
`add_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '注册时间',
`last_login` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后登陆时间',
PRIMARY KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户表';
